In [1]:
element = 'oxygen'
print ('first three characters:', element [0:3])
print ('last three characters:', element [3:6])

first three characters: oxy
last three characters: gen


In [2]:
print (element[:4])
#Question #1

oxyg


In [3]:
print (element[4:])
#Question #1

en


In [4]:
print (element [:])
#Question #1

oxygen


In [5]:
print (element [-1])
#Question #2, would give the last letter

n


In [6]:
print (element [-2])
#Question #2, would give second to last letter

e


In [7]:
print (element [1:-1])
#Question #3, this will skip the first letter and print everything but the last letter

xyge


In [8]:
print (element [3:3])


In [10]:
print (data [3:3, 4:4])
#If we had patient data, this would ouput an empty array because the rows are beginning and ending at the same element which is 3 and the columns are beginning and ending at the same element which is 4

NameError: name 'data' is not defined

In [12]:
print (data [3:3,:])
#This would produce a an arraay with 0 rows because it begins and ends at element 3 and would print all of the column data 

NameError: name 'data' is not defined

In [13]:
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print (A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print (A [1:2,:,3])

IndexError: too many indices for array

In [17]:
stack= numpy.hstack((A[:, :1], A[:, -1:]))
print('stack = ')
print(stack)

stack = 
[[1 3]
 [4 6]
 [7 9]]


In [18]:
npdiff = numpy.array([ 0,  2,  5,  9, 14])


In [19]:
numpy.diff(npdiff)

array([2, 3, 4, 5])

In [20]:
#You would want to do the npdiff function along the x-axis so you could analyze a single patient as they go through various days. If you did this function along the y-axis, you would analyze different patients along the same day 

In [21]:
#If this function was done with at (60x40) matrix, the solution would have a shape of (60x39), because one column would be lost doing the calculations in the data

In [ ]:
#In order to find the largest change of inflammation for each patient, you would first use npdiff to find all the differences between the days for each patient
#After doing npdiff function, you could use np.max () to find the biggest difference for each patient. This function also uses the absolute value so it would not tell you if there is an increase or decrease, only the net change.