In [2]:
3+5*4
#works as a calculator

23

In [7]:
#Using variables to store information
#the 60 is known as an 'assignment'
#Cannot start variable with a number and variables are case sensitive 
weight_kg= 60

In [4]:
#Seeing output of a variable
print(weight_kg)

60


In [6]:
#using functions to do things 
print(weight_kg*weight_kg)

3600


In [10]:
my_number=3
my_float=2.4434343
my_string= 'This is my floating point number: '

In [11]:
#String multiple things together with one print function
print(my_string)

This is my floating point number: 


In [12]:
print(my_string, my_float)

This is my floating point number:  2.4434343


In [15]:
weight_kg_text = 'weight in kilograms:'

In [16]:
print(weight_kg_text, weight_kg)

weight in kilograms: 60


In [17]:
print('weight in pounds:', weight_kg*2.2)

weight in pounds: 132.0


In [19]:
print(weight_kg_text, weight_kg)
print('weight in pounds', weight_kg*2.2)
print (weight_kg)
weight_kg=100
print(weight_kg)


weight in kilograms: 100
weight in pounds 220.00000000000003
100
100


In [20]:
x=5
y=6 
print (x+y)

11


In [21]:
x=y
print (x+y)

12


In [22]:
mass = 47.5 
age = 122 
mass = mass *2 
age= age-20
print (mass, age)

95.0 102


In [23]:
first, second= 'Grace', 'Shawn'
third, fourth= second, first
print (third, fourth)

Shawn Grace


In [24]:
import numpy 

In [25]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter= ',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.]])

In [26]:
medical_data= numpy.loadtxt (fname= 'inflammation-01.csv', delimiter= ',')

In [27]:
import numpy as np

In [28]:
medical_data= np.loadtxt (fname= 'inflammation-01.csv', delimiter= ',')

In [29]:
print(type(medical_data))

<class 'numpy.ndarray'>


In [35]:
#example of an array
a = [1,2,3,4]

In [31]:
print a 

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a)? (<ipython-input-31-d2ddc02e064f>, line 1)

In [32]:
print (a)

[1, 2, 3, 4]


In [34]:
#arrays start at a count of 0 insstead of 1; think of it as number of places away from the start so the first number is 0 away from start
print (a[0])

1


In [37]:
#data types 
##ints= 3,6,100
##floating point numbers: 3.43444, 1.2, 425.4245234235342
print (medical_data.dtype)

float64


In [39]:
print (medical_data.shape)
#prints out as rows,columns

(54, 40)


In [40]:
print ('first value in medical data:', medical_data [0,0])

first value in medical data: 0.0


In [41]:
print ('middle value in data', medical_data [30,20])

middle value in data 6.0


In [42]:
med_data_shape= medical_data.shape

In [45]:
middle_row= int(med_data_shape [0]/2)
middle_column= int(med_data_shape [1]/2)

In [46]:
print (middle_row)
print (middle_column)

27
20


In [47]:
print(medical_data [0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [48]:
bruin= medical_data[:3,36:]

In [50]:
print ('bruiun is:\n', bruin)

bruiun is:
 [[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [51]:
print(np.mean(medical_data))

5.658333333333333


In [52]:
import time
print (time.ctime())

Mon Jan 27 09:42:25 2020


In [53]:
maxval, minval= np.max(medical_data), np.min(medical_data)

In [54]:
stdval= np.std(medical_data)

In [55]:
print ('max:' ,maxval, ', min:', minval, ', stdev:', stdval)

max: 19.0 , min: 0.0 , stdev: 4.352194529455482


In [56]:
patient_0= medical_data [0,:]

In [57]:
print (patient_0)

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


In [58]:
print('max inflammation for patient 0:', np.max(patient_0))

max inflammation for patient 0: 18.0


In [60]:
patient_2= medical_data [1,:]
patient_2_min= np.min(patient_2)
print(patient_2_min)

0.0


In [61]:
print(np.mean(medical_data, axis=1))

[5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1  ]


In [62]:
print(np.mean(medical_data, axis=0))
#average axis 0 is the column  
#average axis 1 is the row 

[ 0.          0.66666667  1.33333333  2.33333333  2.          1.66666667
  4.33333333  3.66666667  5.          6.          6.          7.
  6.33333333  6.33333333  5.          7.66666667  6.33333333 11.33333333
  9.66666667 11.33333333 14.33333333 10.33333333 11.66666667 11.
  8.66666667  8.66666667  8.66666667  6.          7.66666667  4.33333333
  5.66666667  4.66666667  4.33333333  4.33333333  3.33333333  4.
  1.66666667  2.          0.33333333  0.66666667]


In [63]:
def my_func(name): 
    print('Hello', name)

In [64]:
my_func( "Alex")

Hello Alex


In [65]:
def square_minus (x):
    square= x*x 
    square= square- 2 
    return (square)

In [71]:
zzz= square_minus (10,1, "Alex")

aa = square_minus()
print(aa)

TypeError: square_minus() takes 1 positional argument but 3 were given